spring:

  profiles.active: dev
  application.name: registration-service

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate.ddl-auto: validate

jwt:
  secret: ###
  #seconds
  ttl: 1800
